[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# This ensures that the service worker can access any file in the site
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "max-age=0,no-cache,no-store,must-revalidate"

# This ensures that all assets are cached properly
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000"
    
